### ISSUE TITLE
Error in training "trees"

### ISSUE THREAD

**Issue by lancioni** [marcopodda/grapher#1]
While executing general training command `python manage.py train order` under latest pytorch docker image (pytorch version 1.13.0, pyton 3.10.6), the following error happens:

```
Training on trees on order random
Traceback (most recent call last):
  File "/data/grapher/manage.py", line 62, in <module>
    main()
  File "/data/grapher/manage.py", line 33, in main
    exp.train()
  File "/data/grapher/experiment/experiment.py", line 101, in train
    dataset = self.dataset_class(config, self.root, name=self.dataset)
  File "/data/grapher/dataset/manager.py", line 42, in __init__
    self._preprocess_data()
  File "/data/grapher/dataset/manager.py", line 56, in _preprocess_data
    graphlist = self._read_data()
  File "/data/grapher/dataset/manager.py", line 167, in _read_data
    with open(self.raw_dir / "tr.txt", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'DATA/trees/raw/tr.txt'
```

The program is seemingly looking for `tr.txt`, which is not there. Since DATA folder is generated, it looks like an expected file is not created; I cannot find `tr.txt` elsewhere in code, so it is unclear where it is supposed to be actually generated.

Before this error, `ladders`, `community `and `ego` datasets are trained just fine.

Thank you,

Giuliano Lancioni

**Comment by marcopodda** [comment]
Hi Giuliano,
at the moment I cannot find the tree dataset files, I suspect they are on some faculty server but I no longer have access and it might take a while before I find them. Please note that the trees dataset was not part of the original publication but was added later as a request for my Ph.D. thesis committee. In the meantime, I suggest that if you don't specifically need that dataset, you just skip it and use the other ones (which hopefully should work fine). Will write here if anything comes up, but thanks for bringing this up.

**Comment by lancioni** [comment]
Dear Marco,

thank you! Of course there's no specific need for that dataset: I just wanted to be sure that everything was working fine and that I wasn't missing anything!
